[package]
name = "stratum"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.22"
tokio = { version = "1.34.0", features = ["full"] }
serde = "1.0.134"
serde_json = "1.0"
thiserror = "1.0"
sha2 = "0.10"
crypto = "0.5.1"
url = "2.2.2"