name: Compilation

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          cargo build --release
          echo "BUILT_ARCHIVE=$(pwd)/stratum/blob/master/target/release/stratum" >> $GITHUB_ENV

  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: ${{ env.BUILT_ARCHIVE }}