name: Compilation

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          cargo build --release

  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Binary
          path: /home/polina/REPOSIOTORY/stratum/target/release/stratum
      - name: Upload binary to repository
        run: |
          cd ~/REPOSIOTORY
          git config user.email "polinatereschenko16@gmail.com"
          git config --global user.name "polina-tereschenko"
          git add stratum/target/release/stratum
          git commit -m "Add binary release"
          git push
