name: Compilation

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build --release

  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Upload binary to repository
        run: |
          cp /home/polina/REPOSIOTORY/stratum/target/release
          git config user.name "polina-tereschenko"
          git config user.email "polinatereschenko16@gmail.com"
          git add stratum
          git commit -m "Add binary release"
          git push