name: Compilation

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --release

      - name: Generate the artifacts
        run: |
          cd target/release
          chmod +x ./stratum

  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate the artifacts
        uses: skx/github-action-build@master

      - name: Build
        run: |
          cd target/release
          chmod +x ./stratum

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stratum-artifacts
          path: target/release