name: Upload Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build
      run: cargo build --release

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: stratum
        path: target/release/stratum
