name: Build and Upload Binary

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        export PATH="$HOME/.cargo/bin:$PATH"
        rustc --version
        cargo --version
    - name: Build Binary
      run: |
        cargo build --release
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: stratum-binary
        path: /home/polina/REPOSIOTORY/stratum/target/release