name: Compilation

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions/setup-rust@v2
      with:
        profile: minimal
    - name: Build Binary
      run: cargo build --release
    - name: Upload Binary to Releases
      uses: actions/upload-release-asset@v1
      with:
        file: /home/polina/REPOSITORY/stratum/target/release/stratum
        asset_name: stratum
        asset_content_type: application/octet-stream